# Generated by Django 5.1.7 on 2025-04-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('badiiy', 'Badiiy'), ('ilmiy', 'Ilmiy')], default='badiiy', max_length=20),
        ),
    ]
